"""Typed registry boundary for training, evaluation and operator lifecycle actions."""

from typing import Protocol

from adaptive_llm.contracts import ModelManifest, PromotionRequest, TrainingJob
from adaptive_llm.gateway.identity import Identity


class ModelRegistry(Protocol):
    def get(self, version: str, identity: Identity) -> ModelManifest: ...
    def models(self, identity: Identity) -> list[ModelManifest]: ...
    def job(self, job_id: str, identity: Identity) -> TrainingJob | None: ...
    def save_job(self, job: TrainingJob, tenants: list[str]) -> None: ...
    def complete(
        self, job: TrainingJob, manifest: ModelManifest, *, trainer_architecture: str
    ) -> None: ...
    def promote(self, request: PromotionRequest, identity: Identity) -> ModelManifest: ...
    def rollback(
        self, deployment_id: str, identity: Identity, reason: str
    ) -> list[ModelManifest]: ...
